### ISSUE TITLE
諸々修正_2021/04/30

### ISSUE THREAD

**Issue by skm-isy** [telumo/lp-form-proto#7]
【MTGメモ】
｛流れへのFB｝
・課題：「既製品なのかコンサル必要なのかわからない」という顧客課題がある
・上記顧客課題に沿うと、型の選択肢に「どれかわからない」を追加し、既製品 or notの分岐にする、というアイデアの方が良いかも
｛フォーム画面へのFB｝
・見積もり依頼なら、「その他異形」は不要
・複数の型を選択できる必要はない
・相談のフォームにも「添付」の項目ほすい
｛確認画面へのFB｝
・「デザイン料」というのがしっくりこない←「顧客からすると、デザインは決まってるのに、、おかしいやろ」ってなる。正確には3D製作なので、「3Dデザイン費用」か「デザイン料（3D製作）」の方が良さそう？
｛見積もりロジックへのFB｝
・20より大きいのは何個であろうと「要相談」
・取り数 or 枚数いずれかが要相談になったら、合計も要相談（デザインも含めて要相談）

**Comment by telumo** [comment]
- [ ] 相談フォームに添付の項目追加
- [ ] デザイン料の文言修正
